- platform: template
  covers:
    gate:
      device_class: gate
      friendly_name: "Gate"
      value_template: >-
        {% if is_state('input_boolean.portao_status','on') or is_state('binary_sensor.portao_input','off') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.portao
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.portao
      icon_template: >-
        {% if is_state('input_boolean.portao_status','on') or is_state('binary_sensor.portao_input','off') %}
          mdi:gate-arrow-right
        {% else %}
          mdi:gate
        {% endif %}