- platform: command_line
  switches:
    algo_server:
      command_on: /config/algo_poweron.sh
      command_off: /config/algo_poweroff.sh
      command_timeout : 120

- platform: template
  switches:
    evse_admin_rules_inverted:
      unique_id: evse_admin_rules
      friendly_name: evse_admin_rules
      value_template: "{{ is_state('switch.wallbox_charging_rules_enabled', 'off') }}"
      turn_on:
        service: switch.turn_off
        data:
          entity_id: switch.wallbox_charging_rules_enabled
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.wallbox_charging_rules_enabled