# ======================================================================
# 🔌 SWITCHES - Command Line
# ======================================================================
# Switches que executam comandos shell
# ======================================================================

- platform: command_line
  switches:
    algo_server:
      command_on: /config/algo_poweron.sh
      command_off: /config/algo_poweroff.sh
      command_timeout : 120

# ======================================================================
# 🚗⚡ EVSE Admin Rules Switch
# ======================================================================
# MIGRADO para templates/evse_switch.yaml (modern template syntax)
# Data: 30 Janeiro 2026
# Razão: Legacy platform: template deprecated (remove in HA 2026.6)
# 
# Configuração antiga (REMOVIDA):
# - platform: template
#   switches:
#     evse_admin_rules_inverted:
#       unique_id: evse_admin_rules
#       ...
# 
# Nova localização: templates/evse_switch.yaml
# ======================================================================