# ═══════════════════════════════════════════════════════════════════
# SENSOR DE PADRÃO SEMANAL - FATOR DE CONSUMO
# ═══════════════════════════════════════════════════════════════════
#
# Ajusta estimativa de consumo baseado em dia da semana
#
# Lógica:
# - Segunda a Sexta (dias úteis): fator 1.0 (consumo normal)
# - Sábado/Domingo: fator configurável (input_number)
#
# Uso: Multiplicar house_consumption_estimate por este fator
#
# ═══════════════════════════════════════════════════════════════════

sensor:
  - platform: template
    sensors:
      house_consumption_weekday_factor:
        friendly_name: "Fator Consumo Casa (Dia Semana)"
        unique_id: house_consumption_weekday_factor
        icon_template: mdi:calendar-clock
        value_template: >-
          {% set is_weekend = now().weekday() >= 5 %}
          {% if is_weekend %}
            {{ states('input_number.piscina_weekend_consumption_factor')|float(1.0) }}
          {% else %}
            {{ 1.0 }}
          {% endif %}
        attribute_templates:
          day_type: >-
            {% set day = now().weekday() %}
            {% if day == 0 %}Segunda-feira
            {% elif day == 1 %}Terça-feira
            {% elif day == 2 %}Quarta-feira
            {% elif day == 3 %}Quinta-feira
            {% elif day == 4 %}Sexta-feira
            {% elif day == 5 %}Sábado
            {% else %}Domingo
            {% endif %}
          is_weekend: >-
            {{ now().weekday() >= 5 }}
          factor_source: >-
            {% if now().weekday() >= 5 %}
              input_number.piscina_weekend_consumption_factor
            {% else %}
              fixed: 1.0
            {% endif %}
