# ═══════════════════════════════════════════════════════════════════
# SENSOR DE PADRÃO SEMANAL - FATOR DE CONSUMO
# ═══════════════════════════════════════════════════════════════════
#
# Ajusta estimativa de consumo baseado em dia da semana
#
# Lógica:
# - Segunda a Sexta (dias úteis): fator 1.0 (consumo normal)
# - Sábado/Domingo: fator configurável (input_number)
#
# Uso: Multiplicar house_consumption_estimate por este fator
#
# ═══════════════════════════════════════════════════════════════════

- platform: template
  sensors:
    house_consumption_weekday_factor:
      friendly_name: "Fator Consumo Casa (Dia Semana)"
      unique_id: house_consumption_weekday_factor
      unit_of_measurement: "×"
      icon_template: >
        {% if now().weekday() in [5, 6] %}
          mdi:calendar-weekend
        {% else %}
          mdi:calendar-week
        {% endif %}
      value_template: >
        {% if now().weekday() in [5, 6] %}
          {{ states('input_number.piscina_weekend_consumption_factor')|float(1.0) }}
        {% else %}
          1.0
        {% endif %}
      attribute_templates:
        day_type: >
          {% if now().weekday() in [5, 6] %}
            Fim de Semana
          {% else %}
            Dia Útil
          {% endif %}
        is_weekend: >
          {{ now().weekday() in [5, 6] }}
        factor_source: >
          {% if now().weekday() in [5, 6] %}
            input_number.piscina_weekend_consumption_factor
          {% else %}
            fixed (1.0)
          {% endif %}
