#############################################
# Package: Piscina — pH (LLMVision)
#############################################

# --- Helpers ---
# ⚠️ NOTA: As automações deste package foram movidas para automations.yaml
#    para permitir edição via GUI. Este ficheiro contém apenas:
#    - input_boolean, input_number, template sensors, etc.
#    Ver: automations.yaml (procurar por '# Package: piscina_ph.yaml')
#
input_number:
  ph_piscina:
    name: pH Piscina
    min: 0
    max: 14
    step: 0.01
    mode: box
    icon: mdi:pool
    unit_of_measurement: pH
  ph_piscina_raw:
    name: pH Piscina (raw)
    min: -1
    max: 14
    step: 0.01
    mode: box
    icon: mdi:flask
    unit_of_measurement: pH
input_text:
  ph_piscina_backup:
    name: pH — Backup
    max: 12
    mode: text
  ph_piscina_raw_backup:
    name: pH Raw — Backup
    max: 12
    mode: text
template:
- sensor:
  - name: Piscina — pH
    unique_id: piscina_ph_sensor
    state: '{{ states(''input_number.ph_piscina'') | float(0) }}'
    unit_of_measurement: pH
    state_class: measurement
    icon: mdi:pool
sensor:
- platform: statistics
  name: pH — Mín 24h
  unique_id: ph_piscina_min_24h
  entity_id: sensor.piscina_ph
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
  precision: 2
- platform: statistics
  name: pH — Máx 24h
  unique_id: ph_piscina_max_24h
  entity_id: sensor.piscina_ph
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200
  precision: 2
- platform: statistics
  name: pH — Mín 7d
  unique_id: ph_piscina_min_7d
  entity_id: sensor.piscina_ph
  state_characteristic: value_min
  max_age:
    days: 7
  sampling_size: 2000
  precision: 2
- platform: statistics
  name: pH — Máx 7d
  unique_id: ph_piscina_max_7d
  entity_id: sensor.piscina_ph
  state_characteristic: value_max
  max_age:
    days: 7
  sampling_size: 2000
  precision: 2
homeassistant:
  customize:
    input_number.ph_piscina:
      description: Valor de pH validado (6–9) lido por OCR ao ligar a bomba e de hora
        a hora.
    input_number.ph_piscina_raw:
      description: Leitura bruta do pH devolvida pelo LLMVision; -1 quando ilegível.
